### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by davidfmyers** [serverless/serverless-slackbot#1]
Hello,

Has anyone else run into this issue? 

$ serverless resources deploy
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/main/promise.js:677
            throw e;
            ^

TypeError: Cannot read property 'length' of undefined
    at ResourcesDeploy.cliPromptSelectRegion (/usr/local/lib/node_modules/serverless/lib/ServerlessPlugin.js:274:43)
    at /usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:116:20
From previous event:
    at ResourcesDeploy._prompt (/usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:115:4)
From previous event:
    at ResourcesDeploy.resourcesDeploy (/usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:94:8)
    at processImmediate [as _immediateCallback](timers.js:383:17)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:212:25
    at Array.reduce (native)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:211:25)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:182:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:13:36)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3

Thanks!

**Comment by austencollins** [comment]
@davidaws Yes, it's an issue related to Serverless Framework `v0.0.13`.  We've fixed this in `v0.0.14` are pushing the release out within an hour.  Sorry for the inconvenience :(

**Comment by davidfmyers** [comment]
@ac360 No worries man, thanks for the note. I'll update and report back once I see v0.0.14 push.

**Comment by austencollins** [comment]
@davidaws Ok, Serverless Framework v0.0.15 is available on NPM.  Please let me know if you still run into this issue.  We are ready to fix things asap!  Have a good weekend @davidaws :)
